name=File System
version=0.0.1
author=Microsoft
maintainer=Microsoft
sentence=File System
paragraph=SFlashBlockDevice and fatfs_exfuns are part of the framework core (cores/arduino/FileSystem/). This library provides examples only.
category=Data Storage
url=https://www.microsoft.com/en-us/internet-of-things/azure-iot-suite
architectures=stm32f4
